# This workflow will build a Windows executable file

name: PyInstaller-Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pyinstaller
        if exist requirements.txt (pip install -r requirements.txt)
        python -m pip install --no-cache-dir --progress-bar off -U .
    - name: Build an executable file
      run: |
        pyinstaller ./directory_structure_py/src/main.py --clean --onefile -n directory_structure_py.exe
        cp ./for_portable/* ./dist/
        cp ./config/logging.json ./dist/
